/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'WirelessNetworkMsg2'
 * message type.
 */

public class WirelessNetworkMsg2 extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 2;

    /** Create a new WirelessNetworkMsg2 of size 6. */
    public WirelessNetworkMsg2() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new WirelessNetworkMsg2 of the given data_length. */
    public WirelessNetworkMsg2(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 with the given data_length
     * and base offset.
     */
    public WirelessNetworkMsg2(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 using the given byte array
     * as backing store.
     */
    public WirelessNetworkMsg2(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 using the given byte array
     * as backing store, with the given base offset.
     */
    public WirelessNetworkMsg2(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public WirelessNetworkMsg2(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 embedded in the given message
     * at the given base offset.
     */
    public WirelessNetworkMsg2(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg2 embedded in the given message
     * at the given base offset and length.
     */
    public WirelessNetworkMsg2(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <WirelessNetworkMsg2> \n";
      try {
        s += "  [pl_idMsg=0x"+Long.toHexString(get_pl_idMsg())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pl_parentNode=0x"+Long.toHexString(get_pl_parentNode())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pl_originNode=0x"+Long.toHexString(get_pl_originNode())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_idMsg
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_idMsg' is signed (false).
     */
    public static boolean isSigned_pl_idMsg() {
        return false;
    }

    /**
     * Return whether the field 'pl_idMsg' is an array (false).
     */
    public static boolean isArray_pl_idMsg() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_idMsg'
     */
    public static int offset_pl_idMsg() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_idMsg'
     */
    public static int offsetBits_pl_idMsg() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'pl_idMsg'
     */
    public int get_pl_idMsg() {
        return (int)getUIntBEElement(offsetBits_pl_idMsg(), 16);
    }

    /**
     * Set the value of the field 'pl_idMsg'
     */
    public void set_pl_idMsg(int value) {
        setUIntBEElement(offsetBits_pl_idMsg(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_idMsg'
     */
    public static int size_pl_idMsg() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_idMsg'
     */
    public static int sizeBits_pl_idMsg() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_parentNode
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_parentNode' is signed (false).
     */
    public static boolean isSigned_pl_parentNode() {
        return false;
    }

    /**
     * Return whether the field 'pl_parentNode' is an array (false).
     */
    public static boolean isArray_pl_parentNode() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_parentNode'
     */
    public static int offset_pl_parentNode() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_parentNode'
     */
    public static int offsetBits_pl_parentNode() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'pl_parentNode'
     */
    public int get_pl_parentNode() {
        return (int)getUIntBEElement(offsetBits_pl_parentNode(), 16);
    }

    /**
     * Set the value of the field 'pl_parentNode'
     */
    public void set_pl_parentNode(int value) {
        setUIntBEElement(offsetBits_pl_parentNode(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_parentNode'
     */
    public static int size_pl_parentNode() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_parentNode'
     */
    public static int sizeBits_pl_parentNode() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_originNode
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_originNode' is signed (false).
     */
    public static boolean isSigned_pl_originNode() {
        return false;
    }

    /**
     * Return whether the field 'pl_originNode' is an array (false).
     */
    public static boolean isArray_pl_originNode() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_originNode'
     */
    public static int offset_pl_originNode() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_originNode'
     */
    public static int offsetBits_pl_originNode() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'pl_originNode'
     */
    public int get_pl_originNode() {
        return (int)getUIntBEElement(offsetBits_pl_originNode(), 16);
    }

    /**
     * Set the value of the field 'pl_originNode'
     */
    public void set_pl_originNode(int value) {
        setUIntBEElement(offsetBits_pl_originNode(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_originNode'
     */
    public static int size_pl_originNode() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_originNode'
     */
    public static int sizeBits_pl_originNode() {
        return 16;
    }

}
