/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'WirelessNetworkMsg4'
 * message type.
 */

public class WirelessNetworkMsg4 extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 4;

    /** Create a new WirelessNetworkMsg4 of size 28. */
    public WirelessNetworkMsg4() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new WirelessNetworkMsg4 of the given data_length. */
    public WirelessNetworkMsg4(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 with the given data_length
     * and base offset.
     */
    public WirelessNetworkMsg4(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 using the given byte array
     * as backing store.
     */
    public WirelessNetworkMsg4(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 using the given byte array
     * as backing store, with the given base offset.
     */
    public WirelessNetworkMsg4(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public WirelessNetworkMsg4(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 embedded in the given message
     * at the given base offset.
     */
    public WirelessNetworkMsg4(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new WirelessNetworkMsg4 embedded in the given message
     * at the given base offset and length.
     */
    public WirelessNetworkMsg4(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <WirelessNetworkMsg4> \n";
      try {
        s += "  [pl_idMsg=0x"+Long.toHexString(get_pl_idMsg())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pl_LumData=0x"+Long.toHexString(get_pl_LumData())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pl_TempData=0x"+Long.toHexString(get_pl_TempData())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pl_Origin=0x"+Long.toHexString(get_pl_Origin())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [extra_data=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_extra_data(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_idMsg
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_idMsg' is signed (false).
     */
    public static boolean isSigned_pl_idMsg() {
        return false;
    }

    /**
     * Return whether the field 'pl_idMsg' is an array (false).
     */
    public static boolean isArray_pl_idMsg() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_idMsg'
     */
    public static int offset_pl_idMsg() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_idMsg'
     */
    public static int offsetBits_pl_idMsg() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'pl_idMsg'
     */
    public int get_pl_idMsg() {
        return (int)getUIntBEElement(offsetBits_pl_idMsg(), 16);
    }

    /**
     * Set the value of the field 'pl_idMsg'
     */
    public void set_pl_idMsg(int value) {
        setUIntBEElement(offsetBits_pl_idMsg(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_idMsg'
     */
    public static int size_pl_idMsg() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_idMsg'
     */
    public static int sizeBits_pl_idMsg() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_LumData
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_LumData' is signed (false).
     */
    public static boolean isSigned_pl_LumData() {
        return false;
    }

    /**
     * Return whether the field 'pl_LumData' is an array (false).
     */
    public static boolean isArray_pl_LumData() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_LumData'
     */
    public static int offset_pl_LumData() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_LumData'
     */
    public static int offsetBits_pl_LumData() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'pl_LumData'
     */
    public int get_pl_LumData() {
        return (int)getUIntBEElement(offsetBits_pl_LumData(), 16);
    }

    /**
     * Set the value of the field 'pl_LumData'
     */
    public void set_pl_LumData(int value) {
        setUIntBEElement(offsetBits_pl_LumData(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_LumData'
     */
    public static int size_pl_LumData() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_LumData'
     */
    public static int sizeBits_pl_LumData() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_TempData
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_TempData' is signed (false).
     */
    public static boolean isSigned_pl_TempData() {
        return false;
    }

    /**
     * Return whether the field 'pl_TempData' is an array (false).
     */
    public static boolean isArray_pl_TempData() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_TempData'
     */
    public static int offset_pl_TempData() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_TempData'
     */
    public static int offsetBits_pl_TempData() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'pl_TempData'
     */
    public int get_pl_TempData() {
        return (int)getUIntBEElement(offsetBits_pl_TempData(), 16);
    }

    /**
     * Set the value of the field 'pl_TempData'
     */
    public void set_pl_TempData(int value) {
        setUIntBEElement(offsetBits_pl_TempData(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_TempData'
     */
    public static int size_pl_TempData() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_TempData'
     */
    public static int sizeBits_pl_TempData() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pl_Origin
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pl_Origin' is signed (false).
     */
    public static boolean isSigned_pl_Origin() {
        return false;
    }

    /**
     * Return whether the field 'pl_Origin' is an array (false).
     */
    public static boolean isArray_pl_Origin() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pl_Origin'
     */
    public static int offset_pl_Origin() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pl_Origin'
     */
    public static int offsetBits_pl_Origin() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'pl_Origin'
     */
    public int get_pl_Origin() {
        return (int)getUIntBEElement(offsetBits_pl_Origin(), 16);
    }

    /**
     * Set the value of the field 'pl_Origin'
     */
    public void set_pl_Origin(int value) {
        setUIntBEElement(offsetBits_pl_Origin(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pl_Origin'
     */
    public static int size_pl_Origin() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pl_Origin'
     */
    public static int sizeBits_pl_Origin() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: extra_data
    //   Field type: int[], unsigned
    //   Offset (bits): 64
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'extra_data' is signed (false).
     */
    public static boolean isSigned_extra_data() {
        return false;
    }

    /**
     * Return whether the field 'extra_data' is an array (true).
     */
    public static boolean isArray_extra_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'extra_data'
     */
    public static int offset_extra_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'extra_data'
     */
    public static int offsetBits_extra_data(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'extra_data' as a int[]
     */
    public int[] get_extra_data() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_extra_data(0); index0++) {
            tmp[index0] = getElement_extra_data(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'extra_data' from the given int[]
     */
    public void set_extra_data(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_extra_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'extra_data'
     */
    public int getElement_extra_data(int index1) {
        return (int)getUIntBEElement(offsetBits_extra_data(index1), 16);
    }

    /**
     * Set an element of the array 'extra_data'
     */
    public void setElement_extra_data(int index1, int value) {
        setUIntBEElement(offsetBits_extra_data(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'extra_data'
     */
    public static int totalSize_extra_data() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'extra_data'
     */
    public static int totalSizeBits_extra_data() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'extra_data'
     */
    public static int elementSize_extra_data() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'extra_data'
     */
    public static int elementSizeBits_extra_data() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'extra_data'
     */
    public static int numDimensions_extra_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'extra_data'
     */
    public static int numElements_extra_data() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'extra_data'
     * for the given dimension.
     */
    public static int numElements_extra_data(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
